//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodegaBA.WsProductoJavaReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsProductoJavaReference.IWsProductoJava")]
    public interface IWsProductoJava {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsProductoJava/ProductosJava", ReplyAction="http://tempuri.org/IWsProductoJava/ProductosJavaResponse")]
        BuenosAires.Model.Respuesta ProductosJava();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsProductoJava/ProductosJava", ReplyAction="http://tempuri.org/IWsProductoJava/ProductosJavaResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ProductosJavaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsProductoJavaChannel : BodegaBA.WsProductoJavaReference.IWsProductoJava, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsProductoJavaClient : System.ServiceModel.ClientBase<BodegaBA.WsProductoJavaReference.IWsProductoJava>, BodegaBA.WsProductoJavaReference.IWsProductoJava {
        
        public WsProductoJavaClient() {
        }
        
        public WsProductoJavaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsProductoJavaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsProductoJavaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsProductoJavaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta ProductosJava() {
            return base.Channel.ProductosJava();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ProductosJavaAsync() {
            return base.Channel.ProductosJavaAsync();
        }
    }
}
