//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodegaBA.WsObtenerAnwoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsObtenerAnwoReference.IWsAnwo")]
    public interface IWsAnwo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/ObtenerAnwoListaProducto", ReplyAction="http://tempuri.org/IWsAnwo/ObtenerAnwoListaProductoResponse")]
        BuenosAires.Model.Respuesta ObtenerAnwoListaProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/ObtenerAnwoListaProducto", ReplyAction="http://tempuri.org/IWsAnwo/ObtenerAnwoListaProductoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ObtenerAnwoListaProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/ReservarProducto", ReplyAction="http://tempuri.org/IWsAnwo/ReservarProductoResponse")]
        BuenosAires.Model.Respuesta ReservarProducto(string nroserieanwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/ReservarProducto", ReplyAction="http://tempuri.org/IWsAnwo/ReservarProductoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ReservarProductoAsync(string nroserieanwo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsAnwoChannel : BodegaBA.WsObtenerAnwoReference.IWsAnwo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsAnwoClient : System.ServiceModel.ClientBase<BodegaBA.WsObtenerAnwoReference.IWsAnwo>, BodegaBA.WsObtenerAnwoReference.IWsAnwo {
        
        public WsAnwoClient() {
        }
        
        public WsAnwoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsAnwoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAnwoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAnwoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta ObtenerAnwoListaProducto() {
            return base.Channel.ObtenerAnwoListaProducto();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ObtenerAnwoListaProductoAsync() {
            return base.Channel.ObtenerAnwoListaProductoAsync();
        }
        
        public BuenosAires.Model.Respuesta ReservarProducto(string nroserieanwo) {
            return base.Channel.ReservarProducto(nroserieanwo);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ReservarProductoAsync(string nroserieanwo) {
            return base.Channel.ReservarProductoAsync(nroserieanwo);
        }
    }
}
