//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodegaBA.WsConsultaDespachoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsConsultaDespachoReference.IWsGuiaDespacho")]
    public interface IWsGuiaDespacho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiasDespacho", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiasDespachoResponse")]
        BuenosAires.Model.Respuesta ConsultarGuiasDespacho();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiasDespacho", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiasDespachoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ConsultarGuiasDespachoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuia", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuiaResponse")]
        BuenosAires.Model.Respuesta ActualizarEstadoGuia(string nroGd, string estadoGd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuia", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuiaResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ActualizarEstadoGuiaAsync(string nroGd, string estadoGd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsGuiaDespachoChannel : BodegaBA.WsConsultaDespachoReference.IWsGuiaDespacho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsGuiaDespachoClient : System.ServiceModel.ClientBase<BodegaBA.WsConsultaDespachoReference.IWsGuiaDespacho>, BodegaBA.WsConsultaDespachoReference.IWsGuiaDespacho {
        
        public WsGuiaDespachoClient() {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGuiaDespachoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta ConsultarGuiasDespacho() {
            return base.Channel.ConsultarGuiasDespacho();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ConsultarGuiasDespachoAsync() {
            return base.Channel.ConsultarGuiasDespachoAsync();
        }
        
        public BuenosAires.Model.Respuesta ActualizarEstadoGuia(string nroGd, string estadoGd) {
            return base.Channel.ActualizarEstadoGuia(nroGd, estadoGd);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ActualizarEstadoGuiaAsync(string nroGd, string estadoGd) {
            return base.Channel.ActualizarEstadoGuiaAsync(nroGd, estadoGd);
        }
    }
}
